using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;


[RealtimeModel]
public partial class PositionSyncModel
{
    [RealtimeProperty(2,true,true)]
    private Vector3 _position;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class PositionSyncModel : RealtimeModel {
    public UnityEngine.Vector3 position {
        get {
            return _positionProperty.value;
        }
        set {
            if (_positionProperty.value == value) return;
            _positionProperty.value = value;
            InvalidateReliableLength();
            FirePositionDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(PositionSyncModel model, T value);
    public event PropertyChangedHandler<UnityEngine.Vector3> positionDidChange;
    
    public enum PropertyID : uint {
        Position = 2,
    }
    
    #region Properties
    
    private ReliableProperty<UnityEngine.Vector3> _positionProperty;
    
    #endregion
    
    public PositionSyncModel() : base(null) {
        _positionProperty = new ReliableProperty<UnityEngine.Vector3>(2, _position);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _positionProperty.UnsubscribeCallback();
    }
    
    private void FirePositionDidChange(UnityEngine.Vector3 value) {
        try {
            positionDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _positionProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _positionProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.Position: {
                    changed = _positionProperty.Read(stream, context);
                    if (changed) FirePositionDidChange(position);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _position = position;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
